### ISSUE TITLE
yolov8-pose的代码存在问题

### ISSUE THREAD

**Issue by yhwang-hub** [AiQuantPro/AiInfer#2]
我用导出的单batch onnx，最后的推理结果如下：
![Infer_0](https://github.com/AiQuantPro/AiInfer/assets/43528760/f6086360-22cd-4646-b5c4-46d1308df028)

**Comment by CYYAI** [comment]
看教程：https://github.com/AiQuantPro/AiInfer/blob/main/application/yolov8_app/README.md
