### ISSUE TITLE
cuda编译错误

### ISSUE THREAD

**Issue by yohnyang** [AiQuantPro/AiInfer#8]
您好，start+git clone ->cuda build,整个工程代码基本没变，然后配置完本地cuda+trt属性，我用的是cuda11.7 tensorrt843,然后编译.cu时总是报错

identifier "w1" is undefined
...

identifier "v4" is undefined
this declaration has no storage class or type specifier	
expression must have class type but it has type "double (*)(int, const double *)"	
...
MSB3721	命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "D:\program\VS2019\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64" -x cu   -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include"     --keep-dir x64\Release  -maxrregcount=0  --machine 64 --compile -cudart static    -DNDEBUG -D_CONSOLE -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdx64\Release\vc142.pdb /FS   /MD " -o F:\VS2019\TRT_deploy\test_trtv8seg\test_src\x64\Release\cuda_function.cu.obj "F:\VS2019\TRT_deploy\test_trtv8seg\test_src\include\cuda_function.cu"”已退出，返回代码为 1。	test_src	D:\program\VS2019\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.7.targets	790	

----->可以帮忙看下怎么看解决吗？谢谢您

**Comment by CYYAI** [comment]
该项目已废弃，建议使用nndeploy
